// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollcall.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RollCall struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollCall) Reset()         { *m = RollCall{} }
func (m *RollCall) String() string { return proto.CompactTextString(m) }
func (*RollCall) ProtoMessage()    {}
func (*RollCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ab08171660a5d1, []int{0}
}
func (m *RollCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollCall.Unmarshal(m, b)
}
func (m *RollCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollCall.Marshal(b, m, deterministic)
}
func (m *RollCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollCall.Merge(m, src)
}
func (m *RollCall) XXX_Size() int {
	return xxx_messageInfo_RollCall.Size(m)
}
func (m *RollCall) XXX_DiscardUnknown() {
	xxx_messageInfo_RollCall.DiscardUnknown(m)
}

var xxx_messageInfo_RollCall proto.InternalMessageInfo

func (m *RollCall) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *RollCall) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Certificate struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ab08171660a5d1, []int{1}
}
func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Certificate) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RollCall)(nil), "rollcall.RollCall")
	proto.RegisterType((*Certificate)(nil), "rollcall.Certificate")
}

func init() { proto.RegisterFile("rollcall.proto", fileDescriptor_63ab08171660a5d1) }

var fileDescriptor_63ab08171660a5d1 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xca, 0xcf, 0xc9,
	0x49, 0x4e, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x2c,
	0xb8, 0x38, 0x82, 0xf2, 0x73, 0x72, 0x9c, 0x13, 0x73, 0x72, 0x84, 0x24, 0xb8, 0xd8, 0x1d, 0x53,
	0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x21,
	0x2e, 0x16, 0x97, 0xc4, 0x92, 0x44, 0x09, 0x26, 0xb0, 0x30, 0x98, 0xad, 0x64, 0xcd, 0xc5, 0xed,
	0x9c, 0x5a, 0x54, 0x92, 0x99, 0x96, 0x99, 0x9c, 0x58, 0x92, 0x4a, 0x9a, 0x66, 0x27, 0x96, 0x28,
	0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x6b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xf8,
	0xf5, 0x21, 0x9f, 0x00, 0x00, 0x00,
}
