name: Go

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.16.8]
        os: [ubuntu-latest]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Set git to use LF
      # make sure that line endings are not converted on windows
      # as gofmt linter will report that they need to be changed
      run: git config --global core.autocrlf false
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Commit linting
      if: matrix.os == 'ubuntu-latest' && github.ref != 'refs/heads/master'
      uses: wagoid/commitlint-github-action@v2
    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Rust
      run: rustup default 1.51.0
    - name: Build
      run: make tee && make build
    - name: Vet
      run: make vet
    - name: Test with Race Detector
      # do not tests with race detector on windows
      # until the issue with badgerdb memory allocation
      # is solved in this case
      run: make test-race